
Neos:
  ContentRepository:
    Search:
      elasticSearch:
        indexName: typo3cr_testing
        log:
          backendOptions:
            fileBackend:
              logFileURL: '%FLOW_PATH_DATA%Logs/ElasticSearch_Testing.log'
      realtimeIndexing:
        enabled: false
